### ISSUE TITLE
Cannot use "getPropertyValue" to get temp WarningHigh property

### ISSUE THREAD

**Issue by ThaiThu** [openbmc/phosphor-fan-presence#10]
Hi all,

We are modifying some action in fan control.
When we use getPropertyValue function we can get the temperature value from dbus:
object: /xyz/openbmc_project/sensors/temperature/test_temp1
interface: xyz.openbmc_project.Sensor.Value
property: Value

But when we also use "getPropertyValue" to get Temperature's WarningHigh we always get "out_of_range" error.
object:  /xyz/openbmc_project/sensors/temperature/test_temp1
interface:　xyz.openbmc_project.Sensor.Threshold.Warning
property: WarningHigh

The config is as follow:

SetSpeedEvent{
                        Group{
                        {
                            "/xyz/openbmc_project/sensors/temperature/test_temp1",
                            {"xyz.openbmc_project.Sensor.Threshold.Warning",
                             "WarningHigh"}
                        },
                        },
                        std::vector<Action>{
                        make_action(action::count_state_before_speed(
                            static_cast<size_t>(1),
                            static_cast<int64_t>(100),
                            static_cast<uint64_t>(100))
                        ),
                        },
                        Timer{
                            static_cast<std::chrono::seconds>(0),
                            util::Timer::TimerType::repeating
                        },
                        std::vector<Signal>{
                            Signal{
                                match::propertiesChanged(
                                "/xyz/openbmc_project/sensors/temperature/test_temp1",
                                "xyz.openbmc_project.Sensor.Value"
                                ),
                                make_handler(
                                    propertySignal<int64_t>(
                                    "/xyz/openbmc_project/sensors/temperature/test_temp1",
                                    "xyz.openbmc_project.Sensor.Value",
                                    "Value",
                                    handler::setProperty<int64_t>(
                                        "/xyz/openbmc_project/sensors/temperature/test_temp1",
                                        "xyz.openbmc_project.Sensor.Value",
                                        "Value"
                                    ))
                                )
                            },
                          }

Thank you all !!

**Comment by spinler** [comment]
closing. same as https://github.com/openbmc/openbmc/issues/3286
