### ISSUE TITLE
libfan_la_CXXFLAGS is not correctly defined

### ISSUE THREAD

**Issue by mine260309** [openbmc/phosphor-fan-presence#11]
In `Makefile.am`:

```
libfan_la_CXXFLAGS =
	$(SDBUSPLUS_CFLAGS) -flto
```

It is missing a `\` at the end of line `libfan_la_CXXFLAGS = ` and thus it is not correctly defined.
It means that `-flto` is not enabled as well.

And if we fix this and enabled `-flto`, probably we will get build error if we try to build the code locally, due to it's using `ar`, `ranlib` which is missing lto plugin
```
x86_64-openbmc-linux-ar: `u' modifier ignored since `D' is the default (see `U')
x86_64-openbmc-linux-ar: libfan_la-utility.o: plugin needed to handle lto object
x86_64-openbmc-linux-ar: libfan_la-timer.o: plugin needed to handle lto object
x86_64-openbmc-linux-ranlib: .libs/libfan.a(libfan_la-utility.o): plugin needed to handle lto object
x86_64-openbmc-linux-ranlib: .libs/libfan.a(libfan_la-timer.o): plugin needed to handle lto object
```

Instead, it should be using `gcc-ar`, `gcc-ranlib`.

**Comment by spinler** [comment]
@mine260309 Are you planning on fixing?

**Comment by mine260309** [comment]
Yup.
But fixing this may cause build error (see mailing list for details), so it should wait until the above issue is resolved.

**Comment by mine260309** [comment]
I have a *maybe-acceptable* solution on link time optimization in phosphor-time-manager (https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-time-manager/+/12917/)

@spinler If you think it is ok to specify `gcc-ar`, `gcc-ranlib` in `configure.ac`, I could submit a patch here as well

**Comment by mine260309** [comment]
Submitted https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-fan-presence/+/12962/
