### ISSUE TITLE
control: Event adding/removing not processed correctly when preconditions pass/fail

### ISSUE THREAD

**Issue by msbarth** [openbmc/phosphor-fan-presence#12]
When a precondition is configured, events are added and removed based on the precondition state. Once a precondition fails, the associated events should be removed which is not occurring and could the fan control application to leak memory by always adding events and never removing them if the precondition continually passes and fails.

**Comment by amboar** [comment]
Have you tracked this down @msbarth ?

**Comment by msbarth** [comment]
After a few interruptions I think I have finally narrowed it down to a tuple within the fan control event data is not being deleted when the pointer is reset.

**Comment by amboar** [comment]
Have you tried building the application with `-fsanitize=leak` and running it on the bmc? You'll need to build the gcc-sanitizers package for your sdk.

**Comment by msbarth** [comment]
Ah, no I have not. That's good to know for next time (hopefully not necessary), but I have it fixed now and am testing. This leak was introduced when the hwmon service names began having a hash in the name, I think, as I cache the service names for objects to minimize mapper lookups.

**Comment by msbarth** [comment]
Correction, I found that interfaces were being added continuously for object paths that do not exist each time they are attempted to be read (which causes a service name lookup) when an event is added / re-added.
Fix : https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-fan-presence/+/15656/

Another fix found while debugging this issue was that each even signal was not being removed upon event removal.
Fix : https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-fan-presence/+/15313/
