### ISSUE TITLE
Fan control based on priority of temperature sensors

### ISSUE THREAD

**Issue by marthauk** [openbmc/phosphor-fan-presence#20]
In some cases it may be useful for a set of different sensors to control the same fans. In this case it would be useful to be able to prioritize which of the sensors that should be used to control the fans. 

Example:
fan0 is controlled by the `temp_exhaust`sensor under normal circumstances. Another sensor `temp_core` should be used as fallback to control fan0 if `temp_exhaust` for some reason is not functional. 

The priority of `temp_exhaust` should this case be 1 (highest).

**Comment by msbarth** [comment]
When you say `different sensors to control the same fans` are you referring to all the fans within a zone? or individual fans within a single zone?

If you're looking to control all the fans within a zone in this manner, you could setup an event that uses the `use_events_on_state` action to use a set of events based on the state of some object property. So for your example given, the event would be triggered on having `temp_exhaust` being functional or not where an event to control the fans based on the `temp_exhaust` sensor output is loaded when `temp_exhaust` is functional. Then when `temp_exhaust` is nonfunctional, those events get unloaded and a new set of events are loaded that control the fans based on `temp_core`.

An example of this that was recently enabled on a machine:
https://github.com/openbmc/meta-ibm/blob/master/meta-witherspoon/recipes-phosphor/fans/phosphor-fan-control-events-config/witherspoon/events.yaml#L488-L521

and the related object enabling this action:
https://github.com/openbmc/meta-ibm/blob/master/meta-witherspoon/recipes-phosphor/fans/phosphor-fan-control-events-config/witherspoon/events.yaml#L374-L388

**Comment by marthauk** [comment]
I was thinking of all fans within a zone. Thanks for the answer and the example. I'll try to use `use_events_on_state` or the `use_alternate_events_on_state` actions.
