### ISSUE TITLE
clang-format: suggest creating one

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/phosphor-fan-presence#21]
Most openbmc repositories have a `.clang-format` file which can be used to automatically reformat the code.  I was making a change for phosphor-fan-presence and noticed it doesn't have one, which made the effort of refactoring some deprecated code a little more manual.  (Almost every other repository I've been able to do some `git grep | sed ; git grep | xargs clang-format` invocation to automatically fix everything up).

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/32779
