### ISSUE TITLE
Multi-gpio pressence detection

### ISSUE THREAD

**Issue by vsytch** [openbmc/phosphor-fan-presence#27]
Going through the examples in `presence/example`, those only cover the case where the fan presence can be detected from a single gpio. Is currently possible with phosphor-fan-presence to perform presence detection from a combination of multiple gpio inputs?

If it is not possible today, then is it worth adding? I have been following https://gerrit.openbmc.org/c/openbmc/dbus-sensors/+/45997 and the combined usage of a gpio monitoring daemon + entity manager I believe would be sufficient, however that most likely would require some modifications to EM's probing logic.

**Comment by spinler** [comment]
It's just a logical OR of the GPIOs?  The config has an 'anyOf' option where if any of the methods say present it would consider the fan present.  For example the following shows how multiple detections are done for the same fan.


```
    {
        "name": "fan0",
        "path": "/system/chassis/motherboard/fan0",
        "methods": [
            {
                "type": "gpio",
                "key": 6,
                "physpath": "/sys/bus/i2c/devices/7-0061",
                "devpath": "/dev/input/by-path/platform-gpio-keys-polled-event"
            },
            {
                "type": "tach",
                "sensors": ["fan0_0", "fan0_1"]
            }
        ],
        "rpolicy": {
            "type": "anyof"
        }
    },
```

**Comment by vsytch** [comment]
The requirement would be closer to a logic AND. Given a list of gpios, the daemon would need to check if all requested lines are toggled. Entity-Mangaer has support for this in the probing logic by adding `"AND"` in between probe resources.

**Comment by spinler** [comment]
You could make a new class derived from RedundancyPolicy, or maybe from AnyOf, that does a std::all_of instead of an std::any_of like AnyOf does.

Entity Manager's 'AND' is object path agnostic, so  one would have to put unique property values for every fan GPIO value in order for it to not match a fan0 presence indicator with a fan1 one.
